server.port=8080
spring.application.name=leadprocessor

# Aumenta o limite de upload para suportar arquivos CSV grandes (até 100 mil linhas)
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# Variável customizada exigida pelo desafio: tamanho do chunk de processamento
app.lote.chunk-size=1000

# ===============================
# POSTGRESQL DATASOURCE
# ===============================
# Apontando para o container que subimos via docker-compose
spring.datasource.url=jdbc:postgresql://localhost:5432/leaddb
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
# 'validate' garante que o Hibernate não tente criar/alterar as tabelas.
# Deixamos essa responsabilidade 100% para o Flyway.
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# FLYWAY
# ===============================
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
# Evita erros caso o banco esteja vazio na primeira execução
spring.flyway.baseline-on-migrate=true 

# ===============================
# KAFKA
# ===============================
spring.kafka.bootstrap-servers=localhost:9092

# Configurações do Produtor (para enviar os eventos)
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# Configurações do Consumidor (para ler os eventos e atualizar o banco)
spring.kafka.consumer.group-id=lead-processor-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*
